### ISSUE TITLE
Source files without license headers

### ISSUE THREAD

**Issue by puntogil** [mintern-java/primitive#5]
Hi
The following source files are without license headers:
src/main/fmpp/Primitive.fmpp
src/main/fmpp/templates/net/mintern/primitive/Comparators.java.ft
src/main/fmpp/templates/net/mintern/primitive/Primitive.java.ft
src/main/fmpp/templates/net/mintern/primitive/comparators/package-info.java.ft

src/test/java/net/mintern/primitive/PrimitiveTest.java

Please, confirm the licensing of code and/or content/s, and add license headers
https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Clarification
Thanks in advance
Regards
[primitive-1.2.2-license-headers.patch.zip](https://github.com/mintern-java/primitive/files/218822/primitive-1.2.2-license-headers.patch.zip)

**Comment by mintern** [comment]
Thanks for the report and for the suggested patch!

For the sake of my own curiosity, I have a few questions. I hope you don't mind.

1. I read over the Fedora licensing guide, and it seems to indicate that a `LICENSE` file is good enough—it doesn't mention any specific requirement to put the license in every source file.
    1. Is this a special case because `DualPivotQuicksorts.java.ft` and `TimSorts.java.ft` have different licenses, so I need to clarify the copyright and licensing of each file?
    2. If I modify `LICENSE.txt` to mention all of the copyright holders, and if I add something that says, "Except where otherwise indicated, all files are copyright Brandon Mintern licensed under the GPL, yadda yadda..." would that be sufficient?
2. I'm happy that Fedora is using my library! Can you share what you're using it for?

Thanks again!

**Comment by spotrh** [comment]
While a LICENSE is the minimal legal requirement, the best case scenario is that each code file will include some sort of clear license attribution statement. As you can appreciate, code is often reused and copied into other projects. By including a license statement in the header of each source code file, it minimizes the risk of accidental license incompatibilities or copyright infringement. This can be as simple as:
``# Copyright 2016 James T. Kirk <kirk@starfleet.com>``
``# License: GPLv2 or later``

This is not a special case because of your two files with different licenses, however, this illustrates the usefulness.

I hope this helps answer your first question (I'm not the original ticket filer here, but I am the "Fedora Legal" person, and Gil asked me to try to answer you).

**Comment by mintern** [comment]
Thank you very much, Tom! That's very helpful, and completely answers question 1 for me.

I'll add those headers soon.

**Comment by puntogil** [comment]
Sorry for delay in answered at your second question.
We use your library to build apache cassandra [1]
Again thanks
[1] https://bugzilla.redhat.com/show_bug.cgi?id=1324020

**Comment by mintern** [comment]
No problem. That's great! I'm glad my library was helpful.

Thanks for circling back.
